import { defineField, defineType } from 'sanity'

export const carType = defineType({
  name: 'car',
  title: 'Fleet Vehicles (Cars & Buses)',
  type: 'document',
  fields: [
    defineField({
      name: 'name',
      title: 'Vehicle / Car Name',
      type: 'string',
      description: 'e.g. Maruti Suzuki Swift, Hyundai Creta, Fortuner Legender, 35 Seater Luxury Bus',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {
        source: 'name',
        maxLength: 96,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Vehicle Category',
      type: 'string',
      description: 'Primary vehicle type classification',
      options: {
        list: [
          { title: 'Hatchback (Swift, Baleno, i20, Altroz)', value: 'hatchback' },
          { title: 'Sedan (Dzire, Aura, Verna, City, Ciaz)', value: 'sedan' },
          { title: 'SUV 5-Seater (Creta, Seltos, Thar, Brezza, Venue)', value: 'suv5' },
          { title: 'SUV 7-Seater (Innova Crysta, XUV700, Carens, Ertiga)', value: 'suv7' },
          { title: 'Luxury Car (BMW, Mercedes, Audi, Jaguar, Fortuner, Bentley)', value: 'luxury' },
          { title: 'Chauffeur Cab & Airport Transfer', value: 'cabs' },
          { title: 'Luxury Bus & Mini Coach (30 - 50 Seater)', value: 'bus' },
        ],
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'displayPages',
      title: 'Show On Which Pages? (Choose Multiple)',
      type: 'array',
      description: 'Select all website pages and localities where this vehicle should be displayed.',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: '⭐ Homepage (Featured Offers / Fleet Grid)', value: 'home' },
          { title: '🚗 Self Drive Cars (Main Page)', value: 'self-drive-car' },
          { title: '👑 Luxury Cars (Main Page)', value: 'luxurycars' },
          { title: '🚕 Chauffeur Cabs & Airport Transfers', value: 'cabs' },
          { title: '🚙 Hatchbacks Page', value: 'hatchback' },
          { title: '🚘 Sedans Page', value: 'sedan' },
          { title: '🚙 5-Seater SUVs Page', value: 'suv5' },
          { title: '🚐 7-Seater SUVs Page', value: 'suv7' },
          { title: '🚌 Luxury Buses Page', value: 'luxury-buses' },
          { title: '🚌 Outstation Bus Page', value: 'outstation-bus' },
          // Locality Pages
          { title: '📍 Ameerpet', value: 'ameerpet' },
          { title: '📍 Banjara Hills', value: 'banjara-hills' },
          { title: '📍 Begumpet', value: 'begumpet' },
          { title: '📍 Bowenpally', value: 'bowenpally' },
          { title: '📍 Film Nagar', value: 'film-nagar' },
          { title: '📍 Gachibowli', value: 'gachibowli-luxury-car-rental' },
          { title: '📍 Guttala Begumpet', value: 'guttala-begumpet-luxury-car-rental' },
          { title: '📍 Habsiguda', value: 'habsiguda-luxury-car-rental' },
          { title: '📍 Himmatnagar', value: 'himmatnagar' },
          { title: '📍 Hitech City', value: 'hitech-city' },
          { title: '📍 Jubilee Hills', value: 'jubilee-hills' },
          { title: '📍 Khairatabad', value: 'khairatabad-luxury-car-rental' },
          { title: '📍 Kukatpally', value: 'kukatpally' },
          { title: '📍 Langer House', value: 'langer-house' },
          { title: '📍 LB Nagar', value: 'lb-nagar-luxury-car-rental' },
          { title: '📍 Masab Tank', value: 'masab-tank' },
          { title: '📍 Mehdipatnam', value: 'mehdipatnam-luxury-car-rental' },
          { title: '📍 Nampally', value: 'nampally-luxury-car-rental' },
          { title: '📍 Secunderabad', value: 'secunderabad' },
          { title: '📍 Sheikpet', value: 'sheikpet-luxury-car-rental' },
          { title: '📍 SR Nagar', value: 'sr-nagar' },
          { title: '📍 Sun City', value: 'sun-city' },
          { title: '📍 Tarnaka', value: 'tarnaka-luxury-car-rental' },
          { title: '📍 Tolichowki', value: 'tolichowki-luxury-car-rental' },
          { title: '📍 Vijay Nagar Colony', value: 'vijay-nagar-colony' },
          { title: '📍 Yousufguda', value: 'yousufguda' },
        ],
      },
    }),
    defineField({
      name: 'image',
      title: 'Vehicle Image',
      type: 'image',
      description: 'Upload a clean photo or PNG cutout of the vehicle. Recommended: PNG with transparent or clean background.',
      options: {
        hotspot: true,
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'seats',
      title: 'Number of Seats',
      type: 'number',
      description: 'e.g. 5, 7, 8, 30, 35, 40, 50',
    }),
    defineField({
      name: 'modelYear',
      title: 'Model Year',
      type: 'string',
      description: 'e.g. 2023 or 2024',
    }),
    defineField({
      name: 'transmission',
      title: 'Transmission',
      type: 'string',
      options: {
        list: ['Manual', 'Automatic', 'Manual / Automatic'],
      },
    }),
    defineField({
      name: 'fuelType',
      title: 'Fuel Type',
      type: 'string',
      options: {
        list: ['Petrol', 'Diesel', 'Petrol / Diesel', 'Electric', 'CNG'],
      },
    }),
    defineField({
      name: 'kmPerDay',
      title: 'Kilometers per Day',
      type: 'string',
      description: 'e.g. 300 Km/day',
    }),
    defineField({
      name: 'extraKmRate',
      title: 'Extra Km Rate',
      type: 'string',
      description: 'e.g. 9/Km or 11/Km',
    }),
    defineField({
      name: 'extraHrRate',
      title: 'Extra Hour Rate',
      type: 'string',
      description: 'e.g. 300/Hr or 500/Hr',
    }),
    defineField({
      name: 'pricePerDay',
      title: 'Daily Rental Rate (₹)',
      type: 'number',
      description: 'e.g. 2199',
    }),
    defineField({
      name: 'pricePerMonth',
      title: 'Monthly Subscription Rate (₹)',
      type: 'number',
      description: 'e.g. 34999',
    }),
    defineField({
      name: 'monthlySavings',
      title: 'Monthly Savings Tag',
      type: 'string',
      description: 'e.g. Save 48%',
    }),
    defineField({
      name: 'idealFor',
      title: 'Ideal For / Tagline',
      type: 'string',
      description: 'e.g. City commutes & fuel efficiency, Grand weddings & VIP airport pickup',
    }),
    defineField({
      name: 'features',
      title: 'Key Inclusions & Highlights',
      type: 'array',
      of: [{ type: 'string' }],
      description: 'e.g. Air Conditioned, Spacious Boot Space, Fastag Enabled, 24/7 Road Support',
    }),
    defineField({
      name: 'isFeatured',
      title: 'Feature on Homepage Offers Carousel',
      type: 'boolean',
      initialValue: false,
    }),
    defineField({
      name: 'sortOrder',
      title: 'Display Sort Order',
      type: 'number',
      description: 'Lower numbers display first (e.g. 1, 2, 3...)',
      initialValue: 10,
    }),
  ],
  preview: {
    select: {
      title: 'name',
      subtitle: 'category',
      media: 'image',
    },
  },
})
