import { client } from './client'
import { urlForImage } from './image'

// Standard fleet cars fallback data for instant zero-downtime resilience
export const DEFAULT_FLEET = [
  // Hatchbacks
  {
    id: 'swift-manual',
    name: 'Maruti Swift Manual',
    category: 'hatchback',
    image: '/assets/img/cars/Swift.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual Transmission',
    fuelType: 'Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '9/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 1499,
    pricePerWeek: 8999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 24999,
    monthlySavings: 'Save 50%',
    features: ['Zero Security Deposit', 'Spacious Boot', 'Fuel Efficient (22+ km/l)', 'Clean Interiors'],
    displayPages: ['home', 'self-drive-car', 'hatchback'],
  },
  {
    id: 'swift-automatic',
    name: 'Maruti Swift Automatic',
    category: 'hatchback',
    image: '/assets/img/cars/Swift.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Automatic (AMT)',
    fuelType: 'Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '9/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 1699,
    pricePerWeek: 9999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 26999,
    monthlySavings: 'Save 50%',
    features: ['Clutch-Free Driving', 'Touchscreen SmartPlay', 'Smooth City Commute', 'Doorstep Delivery'],
    displayPages: ['home', 'self-drive-car', 'hatchback'],
  },
  {
    id: 'baleno',
    name: 'Maruti Baleno Manual & Automatic',
    category: 'hatchback',
    image: '/assets/img/cars/Baleno.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '9/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 1799,
    pricePerWeek: 10499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 28999,
    monthlySavings: 'Save 50%',
    features: ['Touchscreen Infotainment', 'Apple CarPlay', 'Spacious Legroom', 'Fastag Enabled'],
    displayPages: ['home', 'self-drive-car', 'hatchback'],
  },
  {
    id: 'i20',
    name: 'Hyundai i20 Manual & Automatic',
    category: 'hatchback',
    image: '/assets/img/cars/i20.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '9/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 1899,
    pricePerWeek: 10999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 29999,
    monthlySavings: 'Save 50%',
    features: ['Premium Cabin', 'Rear AC Vents', 'Wireless Charger', '100% Sanitized'],
    displayPages: ['home', 'self-drive-car', 'hatchback'],
  },

  // Mini SUVs
  {
    id: 'fronx',
    name: 'Suzuki Fronx Manual & Automatic',
    category: 'minisuv',
    image: '/assets/img/cars/Fronx.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol / Boosterjet Turbo',
    kmPerDay: '300/Day',
    extraKmRate: '10/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 2199,
    pricePerWeek: 12999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 34999,
    monthlySavings: 'Save 50%',
    features: ['High 190mm Ground Clearance', 'Wireless Apple CarPlay', 'Heads-Up Display', '100% Insured'],
    displayPages: ['home', 'self-drive-car', 'suv5', 'minisuv'],
  },
  {
    id: 'venue',
    name: 'Hyundai Venue Manual & Automatic',
    category: 'minisuv',
    image: '/assets/img/cars/5-Venue.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol / Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '10/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 2299,
    pricePerWeek: 13499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 36999,
    monthlySavings: 'Save 50%',
    features: ['Bluelink Connected Car', 'Power Driver Seat', 'Cornering Lamps', 'Highway Ready'],
    displayPages: ['home', 'self-drive-car', 'suv5', 'minisuv'],
  },
  {
    id: 'punch',
    name: 'Tata Punch Manual & Automatic',
    category: 'minisuv',
    image: '/assets/img/cars/Tata-Punch.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '9/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 1999,
    pricePerWeek: 11999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 31999,
    monthlySavings: 'Save 50%',
    features: ['5-Star Global NCAP Safety', 'Tough SUV Stance', 'Traction Pro Mode', 'Zero Deposit'],
    displayPages: ['home', 'self-drive-car', 'suv5', 'minisuv'],
  },

  // 5-Seater SUVs
  {
    id: 'brezza',
    name: 'Suzuki Brezza Manual & Automatic',
    category: 'suv5',
    image: '/assets/img/cars/5-Brezza.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Smart Hybrid Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '10/Km',
    extraHrRate: '400/Hr',
    pricePerDay: 2499,
    pricePerWeek: 14499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 39999,
    monthlySavings: 'Save 50%',
    features: ['Electric Sunroof', '360 Camera', 'High Reliability', 'Fastag Enabled'],
    displayPages: ['home', 'self-drive-car', 'suv5'],
  },
  {
    id: 'nexon',
    name: 'Tata Nexon Manual & Automatic',
    category: 'suv5',
    image: '/assets/img/cars/5-NEXON.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol / Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '10/Km',
    extraHrRate: '400/Hr',
    pricePerDay: 2499,
    pricePerWeek: 14499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 39999,
    monthlySavings: 'Save 50%',
    features: ['5-Star Safety Champion', 'Ventilated Front Seats', 'Multi-Drive Modes', 'Cruise Control'],
    displayPages: ['home', 'self-drive-car', 'suv5'],
  },
  {
    id: 'harrier',
    name: 'Tata Harrier Manual & Automatic',
    category: 'suv5',
    image: '/assets/img/cars/5-Harrier.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: '2.0L Kryotec Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '12/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 3499,
    pricePerWeek: 19999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 54999,
    monthlySavings: 'Save 50%',
    features: ['Panoramic Sunroof', 'JBL 9-Speaker Audio', 'Dominant Road Stance', 'Terrain Modes'],
    displayPages: ['home', 'self-drive-car', 'suv5'],
  },
  {
    id: 'seltos',
    name: 'Kia Seltos Manual & Automatic',
    category: 'suv5',
    image: '/assets/img/cars/5-Seltos.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol / Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '11/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 2899,
    pricePerWeek: 16999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 46999,
    monthlySavings: 'Save 50%',
    features: ['Dual-Zone Climate Control', 'Panoramic Dual Screens', 'Bose Premium Audio', 'High Highway Comfort'],
    displayPages: ['home', 'self-drive-car', 'suv5'],
  },
  {
    id: 'creta',
    name: 'Hyundai Creta Manual & Automatic',
    category: 'suv5',
    image: '/assets/img/2023-6.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '11/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 2899,
    pricePerWeek: 16999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 46999,
    monthlySavings: 'Save 50%',
    features: ['Panoramic Sunroof', 'Ventilated Seats', 'Cruise Control', 'High Ground Clearance'],
    displayPages: ['home', 'self-drive-car', 'suv5'],
  },
  {
    id: 'thar',
    name: 'Mahindra Thar 4x4 Manual & Automatic',
    category: 'suv5',
    image: '/assets/img/cars/5-Thar.png',
    seats: 4,
    modelYear: '2023',
    transmission: 'Manual 4x4 & Automatic',
    fuelType: '2.2L mHawk Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '12/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 3499,
    pricePerWeek: 19999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 52999,
    monthlySavings: 'Save 50%',
    features: ['True 4x4 Off-Road', 'Convertible Hard Top', 'Muscular Road Presence', 'All-Terrain Tyres'],
    displayPages: ['home', 'self-drive-car', 'suv5'],
  },
  {
    id: 'thar-roxx',
    name: 'Mahindra Thar Roxx 5-Door Manual & Automatic',
    category: 'suv5',
    image: '/assets/img/cars/5-Thar.png',
    seats: 5,
    modelYear: '2024',
    transmission: 'Manual & Automatic',
    fuelType: 'Diesel mHawk',
    kmPerDay: '300/Day',
    extraKmRate: '14/Km',
    extraHrRate: '600/Hr',
    pricePerDay: 3999,
    pricePerWeek: 22999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 59999,
    monthlySavings: 'Save 50%',
    features: ['Spacious 5-Door Cabin', 'Panoramic Skyroof', 'Harman Kardon Audio', 'Unstoppable 4WD'],
    displayPages: ['home', 'self-drive-car', 'suv5'],
  },

  // 7-Seater SUVs & MUVs
  {
    id: 'xuv700',
    name: 'Mahindra XUV 700 Manual & Automatic',
    category: 'suv7',
    image: '/assets/img/cars/7-XUV700.png',
    seats: 7,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Diesel / Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '14/Km',
    extraHrRate: '600/Hr',
    pricePerDay: 3799,
    pricePerWeek: 21999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 58999,
    monthlySavings: 'Save 50%',
    features: ['Panoramic Skyroof', 'Sony 3D Surround Sound', 'AdrenoX AI Cockpit', 'Executive 7-Seater'],
    displayPages: ['home', 'self-drive-car', 'suv7'],
  },
  {
    id: 'carens',
    name: 'Kia Carens Manual & Automatic',
    category: 'suv7',
    image: '/assets/img/cars/7-Kia Carens.png',
    seats: 7,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol / Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '12/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 2799,
    pricePerWeek: 16499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 44999,
    monthlySavings: 'Save 50%',
    features: ['One-Touch Electric Tumble', 'Roof AC Vents for 3 Rows', 'Bose 8-Speaker Audio', 'Family Comfort'],
    displayPages: ['home', 'self-drive-car', 'suv7'],
  },
  {
    id: 'ertiga',
    name: 'Maruti Suzuki Ertiga Manual & Automatic',
    category: 'suv7',
    image: '/assets/img/cars/7-Ertiga.png',
    seats: 7,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Smart Hybrid Petrol / CNG',
    kmPerDay: '300/Day',
    extraKmRate: '11/Km',
    extraHrRate: '400/Hr',
    pricePerDay: 2499,
    pricePerWeek: 14499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 38999,
    monthlySavings: 'Save 50%',
    features: ['Dual AC with 2nd Row Controls', 'Flexible 7-Seat Layout', 'High Fuel Efficiency', 'Doorstep Drop'],
    displayPages: ['home', 'self-drive-car', 'suv7'],
  },
  {
    id: 'innova-crysta',
    name: 'Toyota Innova Crysta Manual & Automatic',
    category: 'suv7',
    image: '/assets/img/cars/7-Innova Crysta.png',
    seats: 7,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: '2.4L Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '14/Km',
    extraHrRate: '600/Hr',
    pricePerDay: 3899,
    pricePerWeek: 22999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 59999,
    monthlySavings: 'Save 50%',
    features: ['Captain Chairs', 'Dual AC Vents', 'Huge Luggage Capacity', 'King of Highways'],
    displayPages: ['home', 'self-drive-car', 'suv7', 'cabs'],
  },
  {
    id: 'innova-hycross',
    name: 'Toyota Innova Hycross Automatic',
    category: 'suv7',
    image: '/assets/img/cars/7-Innova Crysta.png',
    seats: 7,
    modelYear: '2024',
    transmission: 'Automatic (Hybrid)',
    fuelType: 'Strong Hybrid Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '16/Km',
    extraHrRate: '700/Hr',
    pricePerDay: 4499,
    pricePerWeek: 26499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 69999,
    monthlySavings: 'Save 50%',
    features: ['Ottoman Reclining Captain Seats', 'Panoramic Sunroof', 'Silent EV Mode Driving', 'Ultra-Luxury MPV'],
    displayPages: ['home', 'self-drive-car', 'suv7', 'cabs'],
  },
  {
    id: 'fortuner',
    name: 'Toyota Fortuner 4x4 Manual & Automatic',
    category: 'suv7',
    image: '/assets/img/cars/7-Fortuner.png',
    seats: 7,
    modelYear: '2023',
    transmission: 'Manual 4x4 & Automatic',
    fuelType: '2.8L Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '25/Km',
    extraHrRate: '1000/Hr',
    pricePerDay: 5999,
    pricePerWeek: 34999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 89999,
    monthlySavings: 'Save 50%',
    features: ['4x4 Off-Road Dominance', 'VIP Road Presence', 'JBL Audio', 'Ultra-Luxurious Leather'],
    displayPages: ['home', 'self-drive-car', 'luxurycars', 'suv7'],
  },
  {
    id: 'carnival',
    name: 'Kia Carnival Automatic Limousine',
    category: 'suv7',
    image: '/assets/img/cars/7-KiaCarnival.png',
    seats: 7,
    modelYear: '2023',
    transmission: 'Automatic',
    fuelType: '2.2L Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '22/Km',
    extraHrRate: '900/Hr',
    pricePerDay: 5499,
    pricePerWeek: 31999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 84999,
    monthlySavings: 'Save 50%',
    features: ['Dual Sunroofs', 'Electric Sliding Lounge Doors', 'VIP Reclining Captain Chairs', 'Airport VIP'],
    displayPages: ['home', 'self-drive-car', 'luxurycars', 'suv7'],
  },

  // 5-Seater Sedans & Executive Cars
  {
    id: 'verna',
    name: 'Hyundai Verna Manual & Automatic',
    category: 'sedan',
    image: '/assets/img/cars/seden-Verna.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: '1.5L Turbo Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '11/Km',
    extraHrRate: '400/Hr',
    pricePerDay: 2499,
    pricePerWeek: 14499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 39999,
    monthlySavings: 'Save 50%',
    features: ['Bose 8-Speaker Audio', 'Heated & Ventilated Seats', 'Level 2 ADAS Safety', 'Turbo Highway Power'],
    displayPages: ['home', 'self-drive-car', 'sedan'],
  },
  {
    id: 'dzire',
    name: 'Maruti Swift Dzire Manual & Automatic',
    category: 'sedan',
    image: '/assets/img/cars/seden-dzire.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Petrol / CNG',
    kmPerDay: '300/Day',
    extraKmRate: '10/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 1999,
    pricePerWeek: 11999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 29999,
    monthlySavings: 'Save 50%',
    features: ['Plush Rear Seats', 'Excellent Mileage', 'Huge Boot Space', 'Smooth Highway Ride'],
    displayPages: ['home', 'self-drive-car', 'sedan'],
  },
  {
    id: 'ciaz',
    name: 'Maruti Suzuki Ciaz Manual & Automatic',
    category: 'sedan',
    image: '/assets/img/cars/seden-Ciaz.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Smart Hybrid Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '10/Km',
    extraHrRate: '300/Hr',
    pricePerDay: 2299,
    pricePerWeek: 13499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 34999,
    monthlySavings: 'Save 50%',
    features: ['Plush Leather Seats', 'Rear Sunshade', 'Super Smooth Highway Cruise', 'Spacious Legroom'],
    displayPages: ['home', 'self-drive-car', 'sedan'],
  },
  {
    id: 'virtus',
    name: 'Volkswagen Virtus Manual & Automatic',
    category: 'sedan',
    image: '/assets/img/cars/seden-City.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Manual & Automatic (DSG)',
    fuelType: 'TSI Turbo Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '12/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 2799,
    pricePerWeek: 16499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 42999,
    monthlySavings: 'Save 50%',
    features: ['5-Star Global NCAP Safety', '521L Massive Boot', 'Dynamic Paddle Shifters', 'German Build'],
    displayPages: ['home', 'self-drive-car', 'sedan'],
  },
  {
    id: 'slavia',
    name: 'Skoda Slavia Automatic Only',
    category: 'sedan',
    image: '/assets/img/cars/seden-City.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Automatic Only (Torque Converter / DSG)',
    fuelType: 'TSI Turbo Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '12/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 2799,
    pricePerWeek: 16499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 42999,
    monthlySavings: 'Save 50%',
    features: ['Ventilated Front Seats', 'Electric Sunroof', 'Precision Steering Dynamics', 'European Luxury'],
    displayPages: ['home', 'self-drive-car', 'sedan'],
  },
  {
    id: 'scorpio',
    name: 'Mahindra Scorpio-N Automatic Only',
    category: 'suv7',
    image: '/assets/img/cars/7-Compass.png',
    seats: 7,
    modelYear: '2023',
    transmission: 'Automatic Only',
    fuelType: '2.2L mHawk Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '14/Km',
    extraHrRate: '600/Hr',
    pricePerDay: 3499,
    pricePerWeek: 20499,
    weeklySavings: 'Save 25%',
    pricePerMonth: 52999,
    monthlySavings: 'Save 50%',
    features: ['Frequency Selective Damping', 'Sony 12-Speaker 3D Audio', 'Muscular Road Stance', 'Big Daddy SUV'],
    displayPages: ['home', 'self-drive-car', 'suv7', 'sedan'],
  },
  {
    id: 'xl6',
    name: 'Maruti Suzuki XL6 Manual & Automatic',
    category: 'suv7',
    image: '/assets/img/cars/7-Ertiga.png',
    seats: 6,
    modelYear: '2023',
    transmission: 'Manual & Automatic',
    fuelType: 'Smart Hybrid Petrol',
    kmPerDay: '300/Day',
    extraKmRate: '12/Km',
    extraHrRate: '500/Hr',
    pricePerDay: 2699,
    pricePerWeek: 15999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 41999,
    monthlySavings: 'Save 50%',
    features: ['All-Black Leather Interiors', 'Ventilated Front Seats', 'Cruise Control & Captain Chairs'],
    displayPages: ['home', 'self-drive-car', 'suv7', 'sedan'],
  },
  {
    id: 'jaguar-xf',
    name: 'Jaguar XF',
    category: 'luxury',
    image: '/assets/img/jagg.png',
    seats: 5,
    modelYear: '2023',
    transmission: 'Automatic',
    fuelType: 'Petrol',
    kmPerDay: '250/Day',
    extraKmRate: '35/Km',
    extraHrRate: '1500/Hr',
    pricePerDay: 14999,
    pricePerWeek: 89999,
    weeklySavings: 'Save 25%',
    pricePerMonth: 249999,
    monthlySavings: 'Save 45%',
    features: ['British Luxury Styling', 'Meridian Sound System', 'Chauffeur Driven Option', 'Perfect Wedding Car'],
    displayPages: ['home', 'luxurycars'],
  },
  {
    id: 'luxury-bus-35',
    name: '35 Seater Luxury Bus',
    category: 'bus',
    image: '/assets/img/bus2.jpg',
    seats: 35,
    modelYear: '2023',
    transmission: 'Manual',
    fuelType: 'Diesel',
    kmPerDay: '300/Day',
    extraKmRate: '35/Km',
    extraHrRate: '1000/Hr',
    pricePerDay: 16999,
    pricePerWeek: 99999,
    weeklySavings: 'Save 20%',
    pricePerMonth: 0,
    monthlySavings: '',
    features: ['Push-Back Luxury Seats', 'Dual AC Climate Control', 'PA Sound System', 'Expert Chauffeur Included'],
    displayPages: ['luxury-buses', 'outstation-bus'],
  },
];

/**
 * Fetch cars for a specific page slug or category from Sanity CMS with instant fallback.
 */
export async function getCarsForPage(pageSlug, defaultCategory = null) {
  try {
    const query = `*[_type == "car" && ($pageSlug in displayPages || category == $defaultCategory || ($pageSlug == "home" && isFeatured == true))] | order(sortOrder asc, _createdAt desc) {
      _id,
      name,
      "slug": slug.current,
      category,
      displayPages,
      image,
      seats,
      modelYear,
      transmission,
      fuelType,
      kmPerDay,
      extraKmRate,
      extraHrRate,
      pricePerDay,
      pricePerMonth,
      monthlySavings,
      idealFor,
      features,
      isFeatured,
      sortOrder
    }`;

    const cmsCars = await client.fetch(query, {
      pageSlug,
      defaultCategory: defaultCategory || pageSlug,
    });

    if (cmsCars && cmsCars.length > 0) {
      return cmsCars.map((car) => {
        let imageUrl = '/assets/img/cars/Swift.png';
        if (car.image) {
          const generatedUrl = urlForImage(car.image)?.width(800)?.url();
          if (generatedUrl) imageUrl = generatedUrl;
        }

        const dailyPrice = car.pricePerDay || 2000;
        const weeklyPrice = Math.round(dailyPrice * 7 * 0.75);

        return {
          id: car._id,
          name: car.name,
          slug: car.slug || car._id,
          category: car.category || defaultCategory || 'all',
          image: imageUrl,
          seats: car.seats || 5,
          modelYear: car.modelYear || '2023',
          transmission: car.transmission || 'Manual',
          fuelType: car.fuelType || 'Petrol',
          kmPerDay: car.kmPerDay || '300/Day',
          extraKmRate: car.extraKmRate || '9/Km',
          extraHrRate: car.extraHrRate || '300/Hr',
          pricePerDay: dailyPrice,
          pricePerWeek: weeklyPrice,
          weeklySavings: 'Save 25%',
          pricePerMonth: car.pricePerMonth || 32000,
          monthlySavings: car.monthlySavings || 'Save 45%',
          idealFor: car.idealFor || '',
          features: car.features && car.features.length > 0 ? car.features : ['Air Conditioned', '100% Sanitized'],
        };
      });
    }
  } catch (error) {
    console.warn(`Sanity getCarsForPage error for [${pageSlug}]:`, error.message);
  }

  // Fallback to default fleet filtered by category or page
  return DEFAULT_FLEET.filter((car) => {
    if (pageSlug === 'home') return true;
    if (car.displayPages?.includes(pageSlug)) return true;
    if (defaultCategory && car.category === defaultCategory) return true;
    return false;
  });
}
